title:             To be Useful to the World
email:             useworld@naver.com
description:       Seyong Kim's Blog
author:            Seyong Kim
baseurl:           "/"
url:               "https://useworld.github.io"

# Social Profiles
twitter_username:
github_username:   useworld
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
