title:             To be Useful to the World
email:             useworld@naver.com
description:       IT, Programming, Security, Hacking
author:            useworld
baseurl:           "/"
url:               "https://useworld.github.io"

# Social Profiles
twitter_username:
github_username:
facebook_username:

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
