# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Se-yong's Github Page
email: shocora@naver.com
description: Githbu Page Test. Powered by Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://useworld.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  useworld

# Build settings
markdown: kramdown
