# Jekyll configuration

name: Be Useful to the World
description: Security Engineer, Software Developer, ...Hacker

# Url is currently only used only for the RSS feed in feed.xml
url: https://useworld.github.io
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: '/'

author: Useworld
copyright: 2019-2019

share:
  facebook: false
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github:
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: useworld
comments: true

permalink: /:year/:month/:day/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 5

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

#exclude: ['README.md', 'LICENSE']
